package model;

public enum Enumerators {
    BLANK, SNAKE, APPLE, WALL, HEAD, TAIL, WORMHOLE, RESET_GAME, 
    ENABLE_AI, SPEED_UP, SPEED_DOWN, SHOW_HIGHSCORES, OPTIONS, 
    EXIT_GAME, PAUSE_GAME, START_MENU, START_GAME, CHANGE_TRACK, SET_SPEED
}
